#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output={log_dir}/{job_name}-%j.out
#SBATCH --error={log_dir}/{job_name}-%j.err
#SBATCH --partition={partition}
#SBATCH --gres=gpu:{gpu_count}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={memory}
#SBATCH --time={walltime}
#SBATCH --mail-type=END,FAIL

# ===========================================================================
# Experiment: {job_name}
# Model: {model}
# Generated by experiment_dispatch.py
# ===========================================================================

set -euo pipefail

echo "============================================"
echo "  Experiment: {job_name}"
echo "  Host: $(hostname)"
echo "  Date: $(date -Iseconds)"
echo "  GPU:  $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo 'N/A')"
echo "  SLURM Job ID: $SLURM_JOB_ID"
echo "============================================"

# --- Environment setup ---
if command -v conda &>/dev/null; then
    eval "$(conda shell.bash hook)"
    conda activate {conda_env} 2>/dev/null || conda activate base
elif [ -d "$HOME/venv/{conda_env}/bin" ]; then
    source "$HOME/venv/{conda_env}/bin/activate"
elif [ -d "$HOME/.venv/bin" ]; then
    source "$HOME/.venv/bin/activate"
fi

# Verify deps
python -c "import torch; import whisper; import numpy; print(f'torch={{torch.__version__}}, cuda={{torch.cuda.is_available()}}')"

EXPERIMENT_DIR="$HOME/experiments"
OUTPUT_DIR="{remote_output_dir}"
mkdir -p "$OUTPUT_DIR"

echo ""
echo ">>> Running: {script_basename} --model {model}"
echo ""
python "$EXPERIMENT_DIR/{script_basename}" --model {model} --output-dir "$OUTPUT_DIR" {extra_args}

# --- Completion signal ---
SIGNAL_FILE="$OUTPUT_DIR/{job_name}.done"
cat > "$SIGNAL_FILE" <<DONE
{"status": "completed", "job_name": "{job_name}", "timestamp": "$(date -Iseconds)", "slurm_job_id": "$SLURM_JOB_ID"}
DONE

echo ""
echo "============================================"
echo "  Experiment complete: $(date -Iseconds)"
echo "  Signal written to: $SIGNAL_FILE"
echo "============================================"
